# Generated by Django 4.2.16 on 2024-12-05 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_userprofile_verification_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='role',
        ),
    ]
