# Generated by Django 4.2.17 on 2025-01-15 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joinauction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bid_amt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
