# Generated by Django 4.2.17 on 2025-01-15 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joinauction', '0002_alter_bid_bid_amt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='team_name',
            field=models.CharField(default='anonymous', max_length=100),
        ),
    ]
