# Generated by Django 4.2.16 on 2024-12-05 07:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('host_auction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='player_db',
            fields=[
                ('player_id', models.AutoField(primary_key=True, serialize=False)),
                ('player_name', models.CharField(max_length=100)),
                ('matches_played', models.CharField(max_length=10)),
                ('player_role', models.CharField(max_length=50)),
                ('player_age', models.CharField(max_length=5)),
                ('sport', models.CharField(choices=[('Football', 'Football'), ('Cricket', 'Cricket')], max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='tournament',
            name='budget',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='tournament',
            name='max_player',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='tournament',
            name='min_player',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.CreateModel(
            name='player_football',
            fields=[
                ('pfid', models.AutoField(primary_key=True, serialize=False)),
                ('goals', models.CharField(max_length=50)),
                ('assists', models.CharField(max_length=50)),
                ('tackles', models.CharField(max_length=50)),
                ('goals_saved', models.CharField(max_length=50)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='football_player', to='host_auction.player_db')),
            ],
        ),
        migrations.CreateModel(
            name='player_cricket',
            fields=[
                ('pcid', models.AutoField(primary_key=True, serialize=False)),
                ('runs', models.CharField(max_length=50)),
                ('balls_played', models.CharField(max_length=50)),
                ('balls_bowled', models.CharField(max_length=50)),
                ('wickets', models.CharField(max_length=50)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cricket_player', to='host_auction.player_db')),
            ],
        ),
        migrations.CreateModel(
            name='Auction_db',
            fields=[
                ('auction_id', models.AutoField(primary_key=True, serialize=False)),
                ('auction_datetime', models.DateTimeField()),
                ('total_team', models.CharField(max_length=10)),
                ('meeting_id', models.CharField(default=0, max_length=10)),
                ('meeting_password', models.CharField(default=0, max_length=6)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auctions', to='host_auction.tournament')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
