# Generated by Django 4.2.16 on 2024-12-15 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host_auction', '0002_player_db_tournament_budget_tournament_max_player_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_db',
            name='status',
            field=models.CharField(default=0, max_length=2),
        ),
    ]
