# Generated by Django 4.2.16 on 2024-12-15 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('host_auction', '0003_auction_db_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='player_db',
            name='auction',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='host_auction.auction_db'),
        ),
    ]
