# Generated by Django 4.2.17 on 2025-01-07 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('host_auction', '0004_player_db_auction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction_db',
            name='meeting_id',
        ),
        migrations.RemoveField(
            model_name='auction_db',
            name='meeting_password',
        ),
        migrations.RemoveField(
            model_name='auction_db',
            name='total_team',
        ),
        migrations.CreateModel(
            name='Auction_meeting',
            fields=[
                ('mid', models.AutoField(primary_key=True, serialize=False)),
                ('meeting_id', models.CharField(default=0, max_length=10)),
                ('meeting_password', models.CharField(default=0, max_length=6)),
                ('total_team', models.CharField(max_length=10)),
                ('joined_team', models.CharField(default=0, max_length=10)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='host_auction.auction_db')),
            ],
        ),
    ]
