# Generated by Django 4.2.17 on 2025-01-07 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host_auction', '0005_remove_auction_db_meeting_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_db',
            name='auction_status',
            field=models.CharField(default='waiting', max_length=20),
        ),
    ]
