# Generated by Django 4.2.17 on 2025-01-13 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host_auction', '0006_auction_db_auction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='player_db',
            name='is_viewed',
            field=models.BooleanField(default=False),
        ),
    ]
